name: Phpunit
on:
  # Disabled on pull requests
  # pull_request:
  #   branches:
  #     - master
  #   paths-ignore:
  #     - '**.md'
  # push:
  #   branches:
  #     - master
  #   paths-ignore:
  #     - '**.md'
  create:
    tags:
      - v.*
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: vendor/bin/phpunit
